#pragma kernel CSMain

Texture2D<float4> RoughnessMap;
RWTexture2D<unorm float4> GlossinessMap;
uint2 TextureSize;
bool FlipY;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    uint2 uv = id.xy;
    if (FlipY)
        uv.y = TextureSize.y - 1 - uv.y;
    
    float4 roughness = RoughnessMap[uv];
    float glossiness = 1.0 - roughness.r; // invert the roughness to get glossiness
    GlossinessMap[id.xy] = float4(glossiness, glossiness, glossiness, 1.0);
}