#pragma kernel CSMain

Texture2D<float4> BaseMap;
RWTexture2D<float4> SpecularMap;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 baseCol = BaseMap[id.xy];
    float grayscale = dot(baseCol.rgb, float3(0.299, 0.587, 0.114));
    float reflectivity = saturate(grayscale + 0.5);
    float4 specCol = float4(baseCol.r * reflectivity, baseCol.g * reflectivity, baseCol.b * reflectivity, 1.0);
    SpecularMap[id.xy] = specCol;
}